source("R/model.R")
set.seed(26);x<-matrix(runif(90*30),90,30,dimnames=list(paste0("s",1:90),paste0("cg",1:30)))
y<-30*x[,1]-15*x[,2]+rnorm(90);patients<-paste0("p",1:90);cancer<-rep(c("A","B","C"),each=30)
pp<-fit_preprocess(x[1:60,,drop=FALSE],10);before<-pp
z<-apply_preprocess(x[61:90,,drop=FALSE],pp)
stopifnot(identical(pp,before),identical(colnames(z),pp$features))
stopifnot(is.infinite(conformal_q(1:5,1:5)),is.finite(conformal_q(1:30,1:30)))
b<-fit_en(x,y,patients,cancer,max_features=20)
p1<-predict_en(b,x[1,,drop=FALSE]);pall<-predict_en(b,x)
stopifnot(isTRUE(all.equal(p1$predicted_reference_HRDsum,pall$predicted_reference_HRDsum[1],tolerance=1e-10)))
p2<-predict_en(b,x[1,rev(seq_len(ncol(x))),drop=FALSE])
stopifnot(isTRUE(all.equal(p1$predicted_reference_HRDsum,p2$predicted_reference_HRDsum,tolerance=1e-10)))
try_duplicate<-try(fit_en(x,y,rep("same",90),cancer),silent=TRUE);stopifnot(inherits(try_duplicate,"try-error"))
stopifnot(is.na(metrics(rep(1,5),1:5)$R2))
cat("R preprocessing/grouping/order/single-sample/conformal smoke tests passed\n")
